from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

from backend.config.schema import AppConfig


CONFIG_ENV_PREFIX = "NEWMAN_"
INTEGRATION_ENV_KEYS = ("ANYSEARCH_API_KEY",)
LOGGER = logging.getLogger("newman.config")
DISPLAY_LOGGER = logging.getLogger("uvicorn.error")
SENSITIVE_MARKERS = {"api_key", "token", "secret", "password"}
DEPLOY_PROFILE_ENV_KEYS = ("NEWMAN_DEPLOY_PROFILE", "NEWMAN_DEPLOYMENT_PROFILE")
DEPLOYMENT_PROFILES = {"none", "linux_source_default", "macos_source_online"}
_LAST_SETTINGS_REPORT: "ConfigLoadReport | None" = None
_MANAGED_INTEGRATION_ENV: dict[str, str] = {}
PROJECT_CONFIG_TEMPLATE = """# Newman project config
# This file is the project deployment config generated during initialization.
# backend/config/defaults.yaml provides the built-in baseline template and fallback values.
# Keep actual project settings here.
# Model settings and secrets can still be overridden through NEWMAN_* values in .env when needed.

# Optional deployment profile. Leave as "none" for fully manual config, or set
# NEWMAN_DEPLOY_PROFILE in .env / system env to select a host-specific profile.
deployment_profile: "none"

server:
  host: "0.0.0.0"
  port: 8005

auth:
  enabled: true
  # First successful setup will auto-generate the instance access key in .env:
  #   NEWMAN_AUTH__ADMIN_TOKEN=<auto-generated instance key>
  admin_token: null
  cookie_name: "newman_admin_session"
  cookie_secure: false
  cookie_samesite: "lax"
  session_ttl_hours: 168

runtime:
  max_tool_depth: 30
  context_compress_threshold: 0.85
  context_compaction_preserve_recent: 4
  context_compaction_max_failures: 3
  tool_retry_attempts: 3
  tool_retry_backoff_seconds: 1.0
  provider_retry_attempts: 3
  provider_retry_backoff_seconds: 1.0
  provider_max_concurrent_requests: 1
  provider_min_interval_seconds: 0.0

subagents:
  enabled: true
  max_agents_per_run: 5
  max_parallel_agents: 5
  default_max_turns: 200
  lock_wait_timeout_seconds: 30
  sequential_context_token_limit: 2000

evolution:
  enabled: true
  turn_interval: 20
  overlap_user_turns: 6
  max_context_messages: 120
  max_tool_output_chars: 2000
  analysis_max_tokens: 10000
  max_memory_updates_per_run: 1
  max_memory_item_chars: 80
  max_skill_updates_per_run: 3
  max_skill_file_bytes: 200000
  max_skill_total_bytes: 700000

sandbox:
  enabled: true
  backend: "linux_bwrap"
  mode: "workspace-write"
  network_access: false
  writable_roots: []
  timeout: 30
  output_limit_bytes: 10240
  probe_timeout_ms: 5000
  allow_partial_enforcement: false
  require_network_isolation: true
  require_process_isolation: true
  provider_path: null
  env_allowlist:
    - "PATH"
    - "HOME"
    - "LANG"
    - "LC_*"
    - "TMPDIR"
    - "TMP"
    - "TEMP"
    - "NEWMAN_RUNTIME_WORKSPACE"
    - "NEWMAN_PLUGIN_ROOT"
    - "NEWMAN_PLUGIN_NAME"
    - "NEWMAN_LARK_DEFAULT_IM_USER_ID"
    - "NEWMAN_LARK_DEFAULT_IM_IDENTITY"
  allow_automatic_full_access: false

approval:
  level1_blacklist:
    - "rm -rf /"
    - "sudo"
    - "su "
    - "chmod 777 /"
    - "chown root"
  level2_patterns:
    - "write_file_outside_workspace"
    - "process_spawn"
    - "terminal_mutation_or_unknown"
    - "plugin_cli_mutating"
    - "danger_full_access_terminal"
    - "maintain_memory"
    - "maintain_skill"
    - "maintain_plugin"
    - "maintain_tool"
  timeout_seconds: 120

permissions:
  readable_paths:
    - "backend"
    - "frontend"
    - "docs"
    - "backend/tests"
    - "scripts"
  writable_paths:
    - "backend_data/memory"
    - "skills"
    - "plugins"
    - "backend/tools"
  protected_paths:
    - ".env"
    - "newman.yaml"
    - "backend_data/uploads"
    - "backend_data/sessions"
    - "backend_data/audit"

channels:
  feishu:
    enabled: true
    # Use channel_sdk for Feishu -> Newman long-connection inbound.
    # Put app_id/app_secret in .env:
    #   NEWMAN_CHANNELS__FEISHU__APP_ID=cli_xxx
    #   NEWMAN_CHANNELS__FEISHU__APP_SECRET=xxx
    transport: "channel_sdk"
    domain: "https://open.feishu.cn"
    default_turn_approval_mode: "auto_allow"
    require_mention_in_group: true
    allowed_chat_ids: []
    allowed_user_open_ids: []
    reply_timeout_seconds: 20
    dedup_ttl_seconds: 600
  wecom:
    enabled: true

paths:
  workspace: "."
  browse_root: "."
  output_root: "outputs/chat"
  data_dir: "backend_data"
  sessions_dir: "backend_data/sessions"
  memory_dir: "backend_data/memory"
  audit_dir: "backend_data/audit"
  subagents_dir: "backend_data/subagents"
  plugins_dir: "plugins"
  skills_dir: "skills"
  mcp_dir: "backend_data/mcp"
  scheduler_dir: "backend_data/scheduler"
  channels_dir: "backend_data/channels"
  evolution_dir: "backend_data/evolution"
"""


@dataclass
class ConfigLoadReport:
    root: str
    values: dict[str, Any]
    sources: dict[str, str]


def resolve_project_root(project_root: str | None = None) -> Path:
    return Path(project_root or Path(__file__).resolve().parents[2]).resolve()


def get_project_config_path(project_root: str | None = None) -> Path:
    return resolve_project_root(project_root) / "newman.yaml"


def get_project_dotenv_path(project_root: str | None = None) -> Path:
    return resolve_project_root(project_root) / ".env"


def _read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        raise ValueError(f"Expected mapping in config file: {path}")
    return loaded


def _ensure_project_config(path: Path) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PROJECT_CONFIG_TEMPLATE, encoding="utf-8")
    message = f"Created missing project config template: {path}"
    LOGGER.info(message)
    if DISPLAY_LOGGER is not LOGGER:
        DISPLAY_LOGGER.info(message)


def _deep_merge(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    result = dict(base)
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _get_nested_default(data: dict[str, Any], path: tuple[str, ...]) -> Any:
    cursor: Any = data
    for part in path:
        if not isinstance(cursor, dict) or part not in cursor:
            return None
        cursor = cursor[part]
    return cursor


def _coerce_env_value(value: str, expected: Any = None) -> Any:
    if isinstance(expected, list):
        if not value.strip():
            return []
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            loaded = yaml.safe_load(stripped)
            if isinstance(loaded, list):
                return loaded
        return [item.strip() for item in value.split(",") if item.strip()]

    lowered = value.lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    return value


def _read_dotenv(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return parse_dotenv_content(path.read_text(encoding="utf-8"))


def _hydrate_integration_environment(root: Path) -> None:
    """Expose project-managed integration keys to local skill runtimes."""
    dotenv_values = _read_dotenv(root / ".env")
    dotenv_values.update(_read_dotenv(Path.home() / ".newman" / ".env"))
    for key in INTEGRATION_ENV_KEYS:
        configured_value = dotenv_values.get(key, "").strip()
        current_value = os.environ.get(key)
        managed_value = _MANAGED_INTEGRATION_ENV.get(key)
        is_managed_value = current_value == managed_value
        if current_value and not is_managed_value and current_value != configured_value:
            continue
        if configured_value:
            os.environ[key] = configured_value
            _MANAGED_INTEGRATION_ENV[key] = configured_value
        elif is_managed_value:
            os.environ.pop(key, None)
            _MANAGED_INTEGRATION_ENV.pop(key, None)


def parse_dotenv_content(content: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if value and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key] = value
    return values


def _flatten_paths(data: dict[str, Any], prefix: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    items: list[tuple[str, ...]] = []
    for key, value in data.items():
        path = prefix + (str(key).lower(),)
        if isinstance(value, dict):
            items.extend(_flatten_paths(value, path))
        else:
            items.append(path)
    return items


def _assign_nested(target: dict[str, Any], path: tuple[str, ...], value: Any) -> None:
    cursor = target
    for part in path[:-1]:
        cursor = cursor.setdefault(part, {})
    cursor[path[-1]] = value


def _assign_source_map(target: dict[str, str], payload: dict[str, Any], source: str, prefix: tuple[str, ...] = ()) -> None:
    for key, value in payload.items():
        path = prefix + (str(key).lower(),)
        if isinstance(value, dict):
            _assign_source_map(target, value, source, path)
        else:
            target[".".join(path)] = source


def _flatten_leaf_values(data: dict[str, Any], prefix: tuple[str, ...] = ()) -> dict[str, Any]:
    items: dict[str, Any] = {}
    for key, value in data.items():
        path = prefix + (str(key).lower(),)
        if isinstance(value, dict):
            items.update(_flatten_leaf_values(value, path))
        else:
            items[".".join(path)] = value
    return items


def _mask_value(path: str, value: Any) -> Any:
    if any(marker in path for marker in SENSITIVE_MARKERS):
        if value in {None, ""}:
            return value
        return "***"
    return value


def _build_report(root: Path, merged: dict[str, Any], source_map: dict[str, str]) -> ConfigLoadReport:
    values = {
        path: _mask_value(path, value)
        for path, value in sorted(_flatten_leaf_values(merged).items())
    }
    sources = {path: source_map.get(path, "unknown") for path in values}
    return ConfigLoadReport(root=str(root), values=values, sources=sources)


def _log_report(report: ConfigLoadReport) -> None:
    lines = [
        "Config loaded with source trace:",
        *[
            f"  {path} = {report.values[path]!r} ({report.sources[path]})"
            for path in sorted(report.values)
        ],
    ]
    message = "\n".join(lines)
    LOGGER.info(message)
    if DISPLAY_LOGGER is not LOGGER:
        DISPLAY_LOGGER.info(message)


def parse_project_config_content(content: str) -> dict[str, Any]:
    try:
        loaded = yaml.safe_load(content) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"newman.yaml YAML 解析失败: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ValueError("newman.yaml 顶层必须是 YAML 对象")
    return loaded


def _build_env_path_map(defaults: dict[str, Any]) -> dict[str, tuple[str, ...]]:
    env_map: dict[str, tuple[str, ...]] = {}
    for path in _flatten_paths(defaults):
        env_map["_".join(path)] = path
    return env_map


def _env_to_nested(defaults: dict[str, Any], dotenv_values: dict[str, str] | None = None) -> dict[str, Any]:
    env_path_map = _build_env_path_map(defaults)
    nested: dict[str, Any] = {}
    merged_env = dict(dotenv_values or {})
    merged_env.update(os.environ)
    for key, raw_value in merged_env.items():
        if not key.startswith(CONFIG_ENV_PREFIX):
            continue
        raw_path = key[len(CONFIG_ENV_PREFIX) :].lower()
        path = env_path_map.get(raw_path)
        if path is None and raw_path == "deploy_profile":
            path = ("deployment_profile",)
        if path is None and raw_path.startswith("provider_"):
            path = ("models", "primary", raw_path[len("provider_") :])
        if path is None and "__" in raw_path:
            path = tuple(part for part in raw_path.split("__") if part)
        if path is None:
            continue
        expected = _get_nested_default(defaults, path)
        _assign_nested(nested, path, _coerce_env_value(raw_value, expected))
    return nested


def _selected_deployment_profile(merged: dict[str, Any], dotenv_values: dict[str, str]) -> str:
    env_values = dict(dotenv_values)
    env_values.update(os.environ)
    for key in DEPLOY_PROFILE_ENV_KEYS:
        raw_value = env_values.get(key)
        if raw_value is not None and raw_value.strip():
            return raw_value.strip()
    raw_config_value = merged.get("deployment_profile", "none")
    if raw_config_value is None:
        return "none"
    return str(raw_config_value).strip() or "none"


def _load_deployment_profile(root: Path, profile_name: str) -> dict[str, Any]:
    if profile_name not in DEPLOYMENT_PROFILES:
        allowed = ", ".join(sorted(DEPLOYMENT_PROFILES))
        raise ValueError(f"Unknown Newman deployment profile: {profile_name}. Allowed profiles: {allowed}")
    if profile_name == "none":
        return {}
    profile_path = root / "backend" / "config" / "profiles" / f"{profile_name}.yaml"
    profile = _read_yaml(profile_path)
    if not profile:
        raise ValueError(f"Deployment profile is empty or missing: {profile_path}")
    return profile


def _resolve_paths(config: AppConfig, project_root: Path) -> AppConfig:
    data = config.model_dump()
    paths = data["paths"]
    for name, raw_path in list(paths.items()):
        if raw_path is None:
            continue
        path = Path(raw_path)
        if not path.is_absolute():
            paths[name] = str((project_root / path).resolve())
    permissions = data.get("permissions", {})
    for key in ("readable_paths", "writable_paths", "protected_paths"):
        resolved: list[str] = []
        for raw_path in permissions.get(key, []):
            path = Path(raw_path)
            if not path.is_absolute():
                path = (project_root / path).resolve()
            else:
                path = path.resolve()
            resolved.append(str(path))
        permissions[key] = resolved
    return AppConfig.model_validate(data)


def _load_settings_uncached(
    root: Path,
    *,
    project_payload: dict[str, Any] | None = None,
    project_dotenv_values: dict[str, str] | None = None,
) -> tuple[AppConfig, ConfigLoadReport]:
    defaults_path = root / "backend" / "config" / "defaults.yaml"
    project_config_path = root / "newman.yaml"
    user_config_path = Path.home() / ".newman" / "config.yaml"
    project_dotenv_path = root / ".env"
    user_dotenv_path = Path.home() / ".newman" / ".env"

    defaults = _read_yaml(defaults_path)
    _ensure_project_config(project_config_path)
    project = project_payload if project_payload is not None else _read_yaml(project_config_path)
    user = _read_yaml(user_config_path)
    dotenv_values = dict(project_dotenv_values) if project_dotenv_values is not None else _read_dotenv(project_dotenv_path)
    dotenv_values.update(_read_dotenv(user_dotenv_path))
    merged = defaults
    source_map: dict[str, str] = {}
    _assign_source_map(source_map, defaults, "defaults.yaml")
    merged = _deep_merge(merged, project)
    _assign_source_map(source_map, project, "newman.yaml")
    merged = _deep_merge(merged, user)
    _assign_source_map(source_map, user, "~/.newman/config.yaml")

    deployment_profile = _selected_deployment_profile(merged, dotenv_values)
    profile_values = _load_deployment_profile(root, deployment_profile)
    if profile_values:
        merged = _deep_merge(merged, profile_values)
        _assign_source_map(source_map, profile_values, f"deployment_profile:{deployment_profile}")

    env_values = _env_to_nested(merged, dotenv_values)
    merged = _deep_merge(merged, env_values)
    _assign_source_map(source_map, env_values, "environment")

    settings = AppConfig.model_validate_merged(merged)
    settings = _resolve_paths(settings, root)
    report = _build_report(root, settings.model_dump(mode="json"), source_map)
    return settings, report


def read_project_config_text(project_root: str | None = None) -> str:
    path = get_project_config_path(project_root)
    _ensure_project_config(path)
    return path.read_text(encoding="utf-8")


def read_project_dotenv_text(project_root: str | None = None) -> str:
    path = get_project_dotenv_path(project_root)
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def validate_project_config_content(content: str, project_root: str | None = None) -> AppConfig:
    root = resolve_project_root(project_root)
    project_payload = parse_project_config_content(content)
    settings, _ = _load_settings_uncached(root, project_payload=project_payload)
    return settings


def validate_project_dotenv_content(content: str, project_root: str | None = None) -> AppConfig:
    root = resolve_project_root(project_root)
    dotenv_values = parse_dotenv_content(content)
    settings, _ = _load_settings_uncached(root, project_dotenv_values=dotenv_values)
    return settings


@lru_cache(maxsize=1)
def get_settings(project_root: str | None = None) -> AppConfig:
    global _LAST_SETTINGS_REPORT
    root = resolve_project_root(project_root)
    _hydrate_integration_environment(root)
    settings, report = _load_settings_uncached(root)
    _LAST_SETTINGS_REPORT = report

    for path in [
        settings.paths.data_dir,
        settings.paths.sessions_dir,
        settings.paths.memory_dir,
        settings.paths.audit_dir,
        settings.paths.subagents_dir,
        settings.paths.plugins_dir,
        settings.paths.skills_dir,
        settings.paths.mcp_dir,
        settings.paths.scheduler_dir,
        settings.paths.channels_dir,
        settings.paths.evolution_dir,
    ]:
        path.mkdir(parents=True, exist_ok=True)

    return settings


def get_settings_report(project_root: str | None = None) -> ConfigLoadReport:
    global _LAST_SETTINGS_REPORT
    get_settings(project_root)
    if _LAST_SETTINGS_REPORT is None:
        raise RuntimeError("Settings report is unavailable")
    return _LAST_SETTINGS_REPORT


def log_settings_report(project_root: str | None = None) -> ConfigLoadReport:
    report = get_settings_report(project_root)
    _log_report(report)
    return report


def reload_settings(project_root: str | None = None) -> AppConfig:
    global _LAST_SETTINGS_REPORT
    get_settings.cache_clear()
    _LAST_SETTINGS_REPORT = None
    return get_settings(project_root)
