#!/usr/bin/env python3
"""Convert an HTML file (generated by excel2html.py) back to an Excel file (.xlsx).

Reads the embedded data-* attributes from each <td> to reconstruct:
  - Cell values and types
  - Formulas (data-formula)
  - Merged cells (data-merge)
  - Sheet structure

Usage:
    python3 html2excel.py <input.html> [output.xlsx]

If output path is omitted, writes <input>.xlsx next to the HTML file.
"""
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

from runtime_support import configure_current_process_env


configure_current_process_env(Path(__file__).resolve().parents[1])

try:
    import openpyxl
    from openpyxl.utils import get_column_letter, column_index_from_string
except ImportError:
    print("ERROR: openpyxl not installed. Run via run_python.py wrapper.", file=sys.stderr)
    sys.exit(1)


def _col_to_index(col_letter):
    """Convert column letter(s) like 'A', 'AA' to 1-based index."""
    return column_index_from_string(col_letter)


def _parse_cell_ref(ref):
    """Parse 'A1' → (col_letter, row_number)."""
    m = re.match(r'^([A-Z]+)(\d+)$', ref)
    if not m:
        return None, None
    return m.group(1), int(m.group(2))


def _detect_type(val_str, cell_type):
    """Convert a string value back to a Python type based on data-type."""
    if not val_str or cell_type == "empty":
        return None
    if cell_type == "number":
        try:
            if "." in val_str:
                return float(val_str)
            return int(val_str)
        except ValueError:
            return val_str
    if cell_type == "boolean":
        return val_str.lower() in ("true", "1", "yes")
    if cell_type == "date":
        for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S", "%m/%d/%Y"):
            try:
                return datetime.strptime(val_str, fmt)
            except ValueError:
                continue
        return val_str  # fallback: keep as string
    return val_str  # string or formula (formula handled separately)


def html_to_excel(input_path, output_path=None):
    """Main conversion entry point."""
    if not os.path.isfile(input_path):
        print(f"ERROR: File not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        html = f.read()

    # --- Parse sheet blocks ---
    # Each sheet div: <div class="sheet" data-sheet="N" data-merges='[...]' data-formulas='{...}'>
    sheet_pattern = re.compile(
        r'<div\s+class="sheet"\s+'
        r'data-sheet="(\d+)"\s+'
        r"data-merges='([^']*)'\s+"
        r"data-formulas='([^']*)'[^>]*>"
        r'(.*?)</div>',
        re.DOTALL
    )

    sheets = sheet_pattern.findall(html)
    if not sheets:
        # Fallback: try with double-quoted attributes
        sheet_pattern2 = re.compile(
            r'<div\s+class="sheet"\s+'
            r'data-sheet="(\d+)"\s+'
            r'data-merges="([^"]*)"'
            r'(?:\s+data-formulas="([^"]*)")?[^>]*>'
            r'(.*?)</div>',
            re.DOTALL
        )
        sheets = sheet_pattern2.findall(html)

    if not sheets:
        print("ERROR: No sheet data found in HTML. Was this generated by excel2html.py?", file=sys.stderr)
        sys.exit(1)

    # --- Try to extract sheet names from the tab buttons ---
    tab_pattern = re.compile(r'data-sheet="(\d+)"[^>]*>([^<]+)</button>')
    tab_matches = tab_pattern.findall(html)
    sheet_names = {}
    for idx_str, name in tab_matches:
        sheet_names[int(idx_str)] = name.strip()

    # --- Create workbook ---
    wb = openpyxl.Workbook()
    # Remove default sheet
    wb.remove(wb.active)

    for sheet_idx_str, merges_json, formulas_json, sheet_html in sheets:
        sheet_idx = int(sheet_idx_str)
        sheet_name = sheet_names.get(sheet_idx, f"Sheet{sheet_idx + 1}")

        # Ensure valid sheet name (max 31 chars, no special chars)
        safe_name = re.sub(r'[\\/*?\[\]:]', '_', sheet_name)[:31]
        ws = wb.create_sheet(title=safe_name)

        # Parse merges and formulas JSON
        try:
            merge_ranges = json.loads(merges_json) if merges_json.strip() else []
        except json.JSONDecodeError:
            merge_ranges = []
        try:
            formulas = json.loads(formulas_json) if formulas_json.strip() else {}
        except json.JSONDecodeError:
            formulas = {}

        # --- Parse <td> elements ---
        td_pattern = re.compile(
            r'<td\s+'
            r'data-cell="([^"]+)"\s+'
            r'data-type="([^"]+)"\s+'
            r'data-raw="([^"]*)"'
            r'([^>]*)>'
            r'([^<]*)</td>',
            re.DOTALL
        )

        td_matches = td_pattern.findall(sheet_html)

        for ref, cell_type, raw_val, extra_attrs, display_val in td_matches:
            col_letter, row_num = _parse_cell_ref(ref)
            if not col_letter or not row_num:
                continue

            col_idx = _col_to_index(col_letter)
            cell = ws.cell(row=row_num, column=col_idx)

            # Check if this cell is covered by a merge (skip writing)
            is_covered = 'data-covered="true"' in extra_attrs
            if is_covered:
                continue

            # Check for formula
            formula_match = re.search(r'data-formula="([^"]*)"', extra_attrs)
            formula_str = formula_match.group(1) if formula_match else formulas.get(ref, "")

            if formula_str:
                # Write formula (starts with =)
                cell.value = formula_str
            else:
                # Write value
                cell.value = _detect_type(raw_val, cell_type)

        # --- Apply merges ---
        for merge_ref in merge_ranges:
            # merge_ref like "A1:B3"
            try:
                ws.merge_cells(merge_ref)
            except Exception as e:
                print(f"  [WARN] Could not merge {merge_ref}: {e}", file=sys.stderr)

    # --- Determine output path ---
    if output_path is None:
        output_path = os.path.splitext(input_path)[0] + ".xlsx"

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    wb.save(output_path)
    wb.close()

    print(f"[html2excel] Converted: {input_path} → {output_path}")
    print(f"[html2excel] Sheets: {len(sheets)}")
    return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: html2excel.py <input.html> [output.xlsx]", file=sys.stderr)
        sys.exit(1)

    in_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else None
    html_to_excel(in_path, out_path)
